# Automates creation of Release Drafts using Release Drafter
# More Info: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc

on:
  push:
    branches:
      - master
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into the default branch
      - uses: release-drafter/release-drafter@v5
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          java-version: 11
      - run: mvn -DskipTests Verfiy
      - run: mvn test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          java-version: 11
      - run: mvn publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
